app:
  name: betfair
  timezone: Australia/Melbourne
betfair:
  commission_pct_default: 0.05
  max_concurrent_hot: 12
  stream_levels: 3
  auth:
    mode: cert
    sso_host: https://identitysso.betfair.com/api/
    username: ''
    password: ''
    cert_file: ''
    key_file: ''
  rest:
    base_url: https://api.betfair.com/exchange/betting/rest/v1.0/
    timeout_s: 10
  account:
    base_url: https://api.betfair.com/exchange/account/json-rpc/v1
    wallet: AUS
  betting:
    jsonrpc_url: https://api.betfair.com/exchange/betting/json-rpc/v1
    timeout_s: 8
  streaming:
    include_virtual: true
    include_raw: true
    ladder_levels: 3
    heartbeat_ms: 2500
    backoff_ms:
    - 500
    - 1000
    - 2000
    - 5000
    - 10000
    resubscribe_chunk: 50
  orders_stream:
    enabled: true
    ws_url: wss://stream-api.betfair.com:443/ws
    heartbeat_ms: 5000
  orders:
    page_size: 200
  orders_poll:
    interval_s: 1.0
  heartbeat:
    enabled: true
    preferred_timeout_s: 30
ipc:
  transport: inproc
  intents_topic: intents.v1
  reports_topic: reports.v1
slo:
  decision_ack_p50_ms: 60
  decision_ack_p95_ms: 120
logging:
  level: INFO
  file: logs/betfair.log
  retention_days: 14
metrics:
  enabled: true
  port: 8008
  stream_stale_warn_ms: 10000
  ack_p95_warn_ms: 120000
  fee_share_warn: 0.35
  messages_per_gbp_warn: 80
  replace_place_warn: 2.5
  funds:
    mismatch_pct: 5.0
    mismatch_secs: 30.0
execution:
  dry_run: true
  suspend:
    cancel_after_s: 120
  policies:
    persistence:
      sp:
        enabled: true
        min_liability_abs: 5.0
        side_rules:
          BACK: CANCEL_BELOW_MIN
          LAY: CANCEL_BELOW_MIN
risk:
  per_runner_liability_cap: 10.0
  new_risk_per_min_abs: 0.0
accounts:
  poll:
    interval_s: 20
  funds_buffer_abs: 0.0
  funds_buffer_pct: 0.0
simulator:
  record:
    enabled: true
    dir: logs/sim
    snap_interval_s: 10
    max_file_mb: 200
    max_files: 10
    normalize_ws: true
    write_raw_ws: true
    delta_file_prefix: wsdelta
discovery:
  refresh_interval_s: 180
  horizon_hours: 24
  slice_hours: 3
  min_slice_seconds: 300
  grace_post_off_s: 1200
  max_staleness_s: 900
  unsubscribe_enabled: true
  event_type_ids: [7]
  market_types: [WIN, PLACE]
  country_codes: []
  max_results: 1000
edges:
  # ctx-only migration: keep enabled set minimal until other edges are ported
  enabled: [maker]

  registry:
    # Maker now exposes ctx entrypoint `run`
    maker:          src.strategy.edges.maker:run
    # The rest remain registered (not enabled) until ported to ctx-mode:
    parity:         src.strategy.edges.parity:ParityEdge
    suspend_reopen: src.strategy.edges.suspend_reopen:SuspendReopenEdge
    maker_thin:     src.strategy.edges.maker_thin:MakerThinEdge
    mean_revert:    src.strategy.edges.mean_revert:MeanRevertEdge
    bsp_gravity:    src.strategy.edges.bsp_gravity:BspGravityEdge
    xmsr:           src.strategy.edges.xmsr:XMSREdge

  # Maker edge config – your existing knobs preserved
  maker:
    enabled: true
    default_size: 2.0
    min_spread_ticks: 2
    min_depth_best2: 200
    min_lifetime_ms: 2000
    ev_assume_ticks: 0.8
    ev_divergence_boost: 0.2
    fallback_mode: observer
    fallback_size_mult: 0.5
    params:
      A:
        fallback_mode: false
      B:
        fallback_mode: live
    overlays:
      stacking:
        enabled: true
        min_raw_best2_sum: 400
        max_spread_ticks: 6
        size_mult: 0.3
        ttl_bump_ms: 400
        liability_cap_per_runner: 5.0
        levels: 1
        tick_spacing: 1
      queue_aware:
        enabled: false
        min_p_fill: 0.15
        max_ttf_ms: 1500
    hedge:
      enabled: true
      cushion_ticks: 1
      ttl_ms: 3000

  mean_revert:
    enabled: false
    default_size: 1.0
    ttl_ms: 1500
    band_ticks_min: 1.0
    band_ticks_max: 1.5
    max_spread_ticks: 6
    min_raw_best2_sum: 250
    slope_suppress_abs: 0.8
    max_candidates: 2
    bundle_policy: BEST_EFFORT

  sp_gravity:
    enabled: false

  suspend_reopen:
    enabled: false  # disabled until ported to ctx-mode
    reopen_window_ms: 1200
    ttl_ms: 1500
    max_clips_per_reopen: 1
    max_runners: 1
    reopen_max_bank_pct: 0.002
    prefer_with_imbalance: true
    disarm_flap_ms: 4000
    min_spread_ticks: 1
    bundle_policy: ALL_OR_CANCEL

  cross_market:
    enabled: false  # disabled until ported to ctx-mode
    freshness_ms: 100
    cushion_ticks: 2
    min_dual_best2_sum: 200
    ttl_ms: 1200
    top_runners: 3
    place_terms_k: 3
    max_spread_ticks: 6

  identity_book:
    enabled: false

  maker_thin:
    enabled: false
    default_size: 1.0
    min_spread_ticks: 3
    thin_best2_depth_sum_max: 200
    min_lifetime_ms: 2500
    slippage_cushion_ticks: 2
    overlays:
      stacking:
        enabled: false
    hedge:
      enabled: true

  parity:
    bundle_policy: ALL_OR_CANCEL

arbiter:
  lane_of:
    suspend_reopen: suspend_reopen
    maker:          maker
    parity:         cross_market
    maker_thin:     maker
    mean_revert:    mean_revert
    bsp_gravity:    cross_market
    xmsr:           xmsr
    maker_stack:    maker
  lane_priority: [suspend_reopen, maker, cross_market, mean_revert, xmsr]
  hygiene:
    min_lifetime_ms: 2000
  replaces:
    min_interval_ms: 2000
    widen_trigger_ticks: 1

queue_signals:
  window_s: 5
  min_obs_s: 1
  max_ttf_ms: 15000
  eps_size: 0.01
  use_raw: true

profile:
  loop:
    sleep_s: 0.10
    bankroll_refresh_s: 5.0
    intents_per_min_cap: 3600
    max_edges_per_market: 8
    max_plans_per_loop: 64
    debounce_ms: 8
    watchdog_ms: 100
    max_batch_ms: 20

hotloop:
  # placeholders for future Rust thresholds; currently unused by the Python adapter
  queue_window_s: 5
  min_obs_s: 1
  max_ttf_ms: 15000

